export enum ScreenTitle {
  WELCOME = "Welcome",

  BASE_REGISTRATION = "CONNECT SETUP",
  BASE_EDIT = "EDIT BASE",
  CLASSIC_BUTTONS = "BUTTONS",
  BASE_EDIT_INTERACTION_TIMING = "INTERACTION TIMING",
  BASE_FIRMWARE_UPDATE = "CONNECT SETUP",
  BASE_SETUP_PERMISSIONS = "CONNECT SETUP",
  BASES = "HARDWARE",
  BUG_REPORT = "REPORT A BUG",
  BUTTON_ADD = "ADD BUTTON",
  BUTTON_CONVERSION = "MERGE BUTTONS",
  BUTTON_EDIT = "EDIT BUTTON",
  BUTTON_PAIRING = "LINK BUTTON",

  DASHBOARD = "ACTIVITY FEED",
  DASHBOARD_BUTTON = "BUTTON ACTIVITY",
  DASHBOARD_CONTEXT = "CONTEXT ACTIVITY",
  DASHBOARD_FILTERS = "ACTIVITY FILTERS",
  DASHBOARD_MEANING = "MEANING ACTIVITY",
  DASHBOARD_PUSHER = "ACTIVITY",
  DOWNLOAD_SOUND = "EDIT BUTTON",
  RESYNC_BASE = "RESYNC BASE",

  HOUSEHOLD = "HOUSEHOLD",
  HOUSEHOLD_ADD = "ADD MEMBER",
  HOUSEHOLD_EDIT = "EDIT MEMBER",

  LOG = "LOG",
  LOG_DETAILS = "LOG DETAILS",
  LOG_DETAILS_EDIT_BUTTONS = "EDIT BUTTON",
  LOG_DETAILS_EDIT_PUSHER = "EDIT MEMBER",
  LOG_ENTRY_EDIT = "EDIT LOG ENTRY",
  LOG_ENTRY_EDIT_BUTTONS = "EDIT BUTTONS PRESSED",
  LOG_ENTRY_EDIT_PUSHER = "EDIT MEMBER",
  LANDING = "LANDING",
  SETTINGS = "ADVANCED TOOLS",
  SYSTEM_SELECTION = "SET UP SYSTEM",
  UNKNOWN = "UNKNOWN",
  //alpha
  PROFILE_SCREEN = "PROFILE",
  INFORMATION_SCREEN = "INFORMATION",
  LEARNING_SCREEN = "LEARNING",
  GOAL_SCREEN = "GOAL",
  TEST_SCREEN = "TEST",
  SETUP_SCREEN = "SETUP",
  HOME_SCREEN = "HOME",
  MODULE_SCREEN = "MODULE",
  COURSE_SCREEN = "COURSE",

  LESSON_SCREEN = "LESSON",

  //new

  HARDWARE_SCREEN = "HARDWARE",
}
